### ISSUE TITLE
Redshift Distribution for UM baseline catalog

### ISSUE THREAD

**Issue by evevkovacs** [LSSTDESC/cosmodc2#9]
Anita B. checked the z distribution from cosmoDC2 with very fine (.01) binning and observed a series of spikes. This distribution needs to be checked for the UM baseline catalog. If found, the most probable source is a bug in the computation of the redshifts for the low-mass synthetic galaxies.  These redshifts initially come from the UM source snapshot and need to be overwritten with the correct value (computed for the co-moving position for centrals and the target halo redshift for satellites)

**Comment by aphearin** [comment]
Based on the plots below, it looks to me like this bug has been resolved. Tagging @evevkovacs and/or @Andromedanita to report whether these plots convincingly demonstrate that this bug has been fixed. 

## Old results 

![zhist_old](https://user-images.githubusercontent.com/6951595/43975839-8b8f66ee-9ca4-11e8-86c7-f448e6ebe24c.png)
![zevol_gr_old](https://user-images.githubusercontent.com/6951595/43975922-c6108f78-9ca4-11e8-8eb3-10240607f1e8.png)


## New results

![zhist_new](https://user-images.githubusercontent.com/6951595/43975859-96f167ee-9ca4-11e8-91ff-25d5d4636a80.png)
![zevol_gr_new](https://user-images.githubusercontent.com/6951595/43975925-c975a126-9ca4-11e8-9238-fbe1fdec0007.png)

**Comment by Andromedanita** [comment]
Thanks @aphearin , the plots look great! I think the issue has been resolved but maybe you can plot the redshifts obtained from the co-moving distances on top for comparison to make sure they match (since we know the co-moving distances are correct)?

**Comment by evevkovacs** [comment]
This looks convincing but I will do some additional checks on the baseline ctalog (which is where the bug appeared)

**Comment by evevkovacs** [comment]
See also [DESCQA test](https://portal.nersc.gov/project/lsst/descqa/v2/?run=2018-08-10_4&test=Nz_i_rest_frame), which plots the absolute magnitudes in the baseline catalog as a function of redshift for the old and the 2 new baseline catalogs using centrals and satellites for the low-mass synthetic galaxies (labelled cen and sat). Note the bottom right plot for the old catalog (um_v0.1) has a series of outlying points. This is for the very faint galaxies coming from the synthetic galaxies, which had all their redshifts assigned to the snapshot redshift. The plots for the new baseline catalogs do not exhibit this anomaly.

**Comment by evevkovacs** [comment]
One caveat: From [this DESCQA result](https://portal.nersc.gov/project/lsst/descqa/v2/?run=2018-08-10_5&test=readiness_protoDC2) there is still a problem with some outlier values for the redshifts for the version of the baseline catalogs using synthetic centrals. However it is not critical to fix this for the image simulations.

**Comment by evevkovacs** [comment]
The bug in the redshifts for the baseDC2 catalog with centrals was found and fixed. See [here](https://portal.nersc.gov/project/lsst/descqa/v2/?run=2018-08-15_5&test=readiness_baselineDC2&right=2018-08/2018-08-15_5/readiness_baselineDC2/baselineDC2_v0.4_cens_oldcolor/)
